<?php
/**
 * Created by PhpStorm.
 * User: eric
 * Date: 15/03/18
 * Time: 22:14
 */

namespace App\Controller;

use FOS\OAuthServerBundle\Controller\TokenController as BaseController;
use Symfony\Component\HttpFoundation\Request;
use OAuth2\OAuth2;
use Symfony\Component\DependencyInjection\ContainerInterface as Container;
use Symfony\Component\Routing\Annotation\Route;


class TokenController extends BaseController
{
    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/oauth/v2/token")
     */
    public function tokenAction(Request $request)
    {
        $data = (array)$request->getContent();
        $content = (array)json_decode($data[0]);

        $paramBag = new \Symfony\Component\HttpFoundation\ParameterBag;
        $paramBag->add($content);

        $request->request = $paramBag;

        return parent::tokenAction($request); // TODO: Change the autogenerated stub
    }
}