#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api'

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"