parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Service\:
        resource: '../src/Service'
        tags: ['service.service_arguments']

    fos_oauth_server.server:
        class: OAuth2\OAuth2
        autowire: true
        public: true
        arguments:
            $storage: '@fos_oauth_server.storage'

    fos_oauth_server.controller.token:
        class: FOS\OAuthServerBundle\Controller\TokenController
        autowire: true
        public: true
        arguments:
            $server: '@fos_oauth_server.server'

    App\Command\CreateOauthClientCommand:
        arguments:
            $client_manager: '@fos_oauth_server.client_manager.default'

    OAuth2\OAuth2:
        alias: 'fos_oauth_server.server'
        public: true

# Event Listeners
    oauth_event_listener:
        class:  App\EventListener\Security\OAuthEventListener
        public: true
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onPostAuthorizationProcess }

    login_listener:
        class:  App\EventListener\Security\LoginListener
        public: true
        autowire: true
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }



